# Generated by Django 6.0.1 on 2026-02-04 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("weight", models.FloatField(help_text="Weight in kg")),
                ("height", models.FloatField(help_text="Height in cm")),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary (little or no exercise)"),
                            ("light", "Lightly Active (light exercise 1-3 days/week)"),
                            (
                                "moderate",
                                "Moderately Active (moderate exercise 3-5 days/week)",
                            ),
                            ("active", "Very Active (hard exercise 6-7 days/week)"),
                            (
                                "extra",
                                "Extra Active (very hard exercise & physical job)",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose", "Lose Weight"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Gain Weight"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "target_weight",
                    models.FloatField(
                        blank=True, help_text="Optional target weight in kg", null=True
                    ),
                ),
                (
                    "diet_preference",
                    models.CharField(
                        choices=[
                            ("balanced", "Balanced Diet"),
                            ("vegetarian", "Vegetarian (no meat)"),
                            ("vegan", "Vegan (no animal products)"),
                            ("keto", "Ketogenic (high fat, low carb)"),
                            ("paleo", "Paleo (whole foods)"),
                            ("gluten_free", "Gluten-Free"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                (
                    "bmr",
                    models.FloatField(
                        blank=True,
                        help_text="Basal Metabolic Rate (calories/day)",
                        null=True,
                    ),
                ),
                (
                    "tdee",
                    models.FloatField(
                        blank=True,
                        help_text="Total Daily Energy Expenditure (calories/day)",
                        null=True,
                    ),
                ),
                (
                    "daily_calorie_target",
                    models.FloatField(
                        blank=True,
                        help_text="Daily calorie target based on goal",
                        null=True,
                    ),
                ),
                (
                    "protein_target",
                    models.FloatField(
                        blank=True, help_text="Daily protein target (grams)", null=True
                    ),
                ),
                (
                    "carbs_target",
                    models.FloatField(
                        blank=True, help_text="Daily carbs target (grams)", null=True
                    ),
                ),
                (
                    "fat_target",
                    models.FloatField(
                        blank=True, help_text="Daily fat target (grams)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_date", models.DateField()),
                ("meals", models.JSONField(default=dict)),
                ("total_calories", models.FloatField()),
                ("total_protein", models.FloatField()),
                ("total_carbs", models.FloatField()),
                ("total_fat", models.FloatField()),
                (
                    "was_followed",
                    models.BooleanField(
                        blank=True, help_text="Did user follow this plan?", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to="diet.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Plan",
                "verbose_name_plural": "Meal Plans",
                "ordering": ["-plan_date"],
                "unique_together": {("profile", "plan_date")},
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField()),
                ("weight", models.FloatField(help_text="Weight in kg")),
                (
                    "calories_consumed",
                    models.FloatField(default=0, help_text="Total calories consumed"),
                ),
                (
                    "protein_consumed",
                    models.FloatField(default=0, help_text="Protein consumed (grams)"),
                ),
                (
                    "carbs_consumed",
                    models.FloatField(default=0, help_text="Carbs consumed (grams)"),
                ),
                (
                    "fat_consumed",
                    models.FloatField(default=0, help_text="Fat consumed (grams)"),
                ),
                (
                    "water_intake",
                    models.FloatField(default=0, help_text="Water consumed (liters)"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Any notes for the day"),
                ),
                (
                    "energy_level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        help_text="Energy level (1-10)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="diet.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Log",
                "verbose_name_plural": "Daily Logs",
                "ordering": ["-log_date"],
                "unique_together": {("profile", "log_date")},
            },
        ),
    ]
